default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: itsm_user
      password: itsm_pass
      port: 5432
      dbname: itsm_db
      schema: dbt_itsm
      threads: 1
